# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f010a7040d66c3108061a6bb116ed181e23b61f3ca89ef9991da3d053948b2d69168494efdddb24d9571796b68e86519281a52456998ad5e7d310cc9fa47211

test:
  secret_key_base: 570f664e2416acc8b7e4d80584064eaf6c40b9785ccbe57cf714a65e40d0b8b095846c86f329495625a3df60a86778f2a52df2412b23d79957e8949e414aa70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
